//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess1
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeV2
    {
        public long EMPID { get; set; }
        public string OpCoemailend { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string level { get; set; }
        public string managerID { get; set; }
        public string emailRelationship { get; set; }
        public Nullable<int> OpCo { get; set; }
    
        public virtual opcoRef opcoRef { get; set; }
    }
}
